script:
- "./parrot-csd build"
deploy:
  provider: releases
  api_key:
    secure: D/9KnWYaneUHolje1yOTU/C33+8vIMlZ/CCGbRvSS2HZmU/qQnYmWLE1p9vOxwbVqhReYpKYtaRxUR8P3PWekvQDr2AG7bqXVsQs6L+hJicXtSyLR5OdLOKRDhhtx4U4eP3vdCZ3gah3giAaqx6gkpVO8TWTcaeYULiJejZqwbDItDONk0WqTPChWC+yrQgugkEZPKWLbXsC9JohgdHJJWH1vJoOCrSfW825+1h6j9+syxoQHdIPP7c+TWlNxfKq0OVySVF7oFQt879Ce4fYn/iRG7Vytjw+4DJR9pDShijow8VsrzUSBOvkbgY9VX4/jH2BRkuDG4pcbYOXIyOZ5Wg+79HrUJ/+4UPLTdLxBqjf21Tb+AhIGKzxEgGAJydotGl/lRFCjCFUKiPxNneqaO8bLdVXflbrzJ+BOgpyJ0h0hpU30XaSBDUgh3IOzrnySQCheRGU6QV2PPCH9D2i++GPzL/Xi0idgNI9uf2cifUk6XTEUYhGBRNhRnhe9FB99Jz+/dfWSlX2BS9MzqVZihGrH18ZCPtNesNT9S3bM00rT1NtobvJ7QR8EKk080uQAs1fiZPViNQmLXa2pSMCS4Bv6FzRMyl92vOmAAw1I8e8uRt2iT2/gS56ZaNgt9um82x+WlnNVG553jejv7nFAZoNz+S/y/KlzDcjM75JEPo=
  file_glob: true
  skip_cleanup: true
  file:
  - "KAFKA_REST/target/*.jar"
  - "SCHEMA_REGISTRY/target/*.jar"
  - "PARROT_MANAGER/target/*.jar"
  - "PARROT_STREAM/target/*.jar"
  on:
    tags: true
    repo: parrot-stream/parrot-cloudera-csds
